base_path = "/Users/leverest/Documents/02_project/02_Python/05_data_science/skd/"
path_movie_names = base_path + "data/movie_names.csv"
path_movie_omdb = base_path + "data/movie_omdb.csv"
path_movie_dir_actor = base_path + "data/movie_dir_actor.csv"
path_movie_ethnicity = base_path + "data/movie_ethnicity.csv"
omdb_key = "601f2614"
